name: deploy-toy-website-environments
concurrency: toy-company

on: 
  push:
    branches: 
      - main
    paths:
      - 'deploy/**'
  workflow_dispatch:

env:


jobs:
  lint: 
    uses: ./.github/workflows/lint.yml
